### ISSUE TITLE
Add the possibility to enable multipart

### ISSUE THREAD

**Issue by bokzor** [drinkwater-io/drinkwater-java#25]
Right now It is impossible to use a route with multipart content.

Exhausted after delivery attempt: 1 caught: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8081/xxx?amp%3BthrowExceptionOnFailure=true with statusCode: 415

**Comment by CedricDumont** [comment]
This error is related with the AsProxy() service.
in RouteBuilders#mapHttpProxyRoutes() add the enablemulti-partFilter=false option
check http://camel.apache.org/jetty.html and search enablemulti-partFilter
